server:
	javac History.java
	javac Server.java
	java Server 9879

clientA:
	javac Client.java
	java Client A 1234 localhost 9879

clientB:
	javac Client.java
	java Client B 1234 localhost 9879


clean:
	rm *.class
